### ISSUE TITLE
Add Max to the contributors list

### ISSUE THREAD

**Issue by gmajan** [moja-global/FLINT#1]
I will add Max in the comment to this issue. I will also change the names of the maintainers in the Readme page of this rep.

**Comment by gmajan** [comment]
@all-contributors please add @mfellows  for code

Shall I add all the contributors who are in the SLEEK list?

**Comment by gmajan** [comment]
@all-contributors please add @mfellows for code

**Comment by mtbdeligt** [comment]
Max has been added to the contributors list resolving the issue.
