### ISSUE TITLE
Add video link, Remove dead links, Reduce grammatical errors.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/FLINT#101]
**What does the current documentation state?**
_[ A few changes in the current README]_

**Where is this stated?**
https://github.com/moja-global/FLINT

**Why do you want to improve the statement?**
Because _FLINT is moja global's flagship software, making the README an important document_. Refinement of the README may help.

**Proposed statement**
**I would like to:**
**1) Reduce the number of dead links in the document.**
**2) Reduce grammatical errors / More the document crisper.**
**3) Add the video link to the document.**

**Additional info**
If there are ways I come across to better the documentation along the way, I would like to imply them.

**Comment by HarshCasper** [comment]
Thanks @chicken-biryani 

I will start work on it from tomorrow.

**Comment by chicken-biryani** [comment]
Hey, @HarshCasper I am actually already on it! Maybe you could better my work or recommend ways to improve the work I did?
