### ISSUE TITLE
Fix typo in README.MD

### ISSUE THREAD

**Issue by DMHoodoo** [moja-global/FLINT#30]
**What does the current documentation state?**
On Line 53 in [README.md](https://github.com/moja-global/FLINT/blob/master/README.md)
The **_you_** is supposed to be _**your**_
> Once this has completed, start a command shell in **_you_** FLINT repository folder. Now use the following commands to create the Visual Studio solution:

**Where is this stated?**
Line 53 in [README.md](https://github.com/moja-global/FLINT/blob/master/README.md)

**Why do you want to improve the statement?**
Incorrect spelling/grammar.

**Proposed statement**
> Once this has completed, start a command shell in **_your_** FLINT repository folder. Now use the following commands to create the Visual Studio solution:

**Additional info**
Just a small non-issue. Thought I'd point it out.

**Comment by gmajan** [comment]
Thank you for pointing out this typo. Well done.
