### ISSUE TITLE
In Installing FLINT , if we install MOJA Libraries when we click on " Configure button" the following error occured

### ISSUE THREAD

**Issue by parth-gr** [moja-global/FLINT#32]
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:98 (GenerateSourceGroups):
  Unknown CMake command "GenerateSourceGroups".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.15)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring incomplete, errors occurred!
See also "C:/Users/Hp/vcpkg/buildtrees/geos/src/3.6.3-7d98e22225/src/build/CMakeFiles/CMakeOutput.log".

**Comment by parth-gr** [comment]
By reading the error, i understood the CMakelists.txt must be upgraded, 
and also the version of Cmake given in README should be updated, 
and I am also getting error in installing Zipper and Turtle while configuration.

I understood it well should I work on this issue.

**Comment by gmajan** [comment]
Thank you for finding this issue. If you can work on this that would be great. Thank you very much.

**Comment by parth-gr** [comment]
Sure sir

**Comment by malfrancis** [comment]
Thanks Parth, I could not reproduce and I think the warning is coming from the geos library which is a dependency of GDAL.
