### ISSUE TITLE
Country implementations with reproducible results

### ISSUE THREAD

**Issue by floybix** [moja-global/FLINT#37]
Hi there.

I would like to try out FLINT to see how it works in practice and how the various modules are implemented.

I was happy to find the data files from Kenya in `Examples/data.zip` -- however, I do not know how they should be used with FLINT in an actual model run.

Ideally, I would like to see the data files from an actual country implementation, together with the commands for reproducing its key reported results.

I can see you are committed to openness in science and code; I admire and appreciate that! The ultimate expression of that would be reproducible results from country implementations.

Best wishes

**Comment by gmajan** [comment]
Hi Felix,

Thank you for having a look at our code. For an implementable example, I suggest that you look at this one. https://github.com/moja-global/Google_Summer_of_Code/tree/master/Examples

We cannot share country wide data as the users own their own data and run it through FLINT. We are happy to share data that users make public but few users do. 

Please have a look at the example above and if you still would like to have additional info let us know. We will contact a few users and ask them to share.

Good luck. Let us know how you go.

**Comment by floybix** [comment]
Thanks for pointing me to that example. I got it to run after adding `pip install SQLAlchemy`.

It's disappointing that Australia's FullCAM is not open source, thus not meeting the official [Digital Service Standard](https://www.dta.gov.au/help-and-advice/digital-service-standard/digital-service-standard-criteria/8-make-source-code-open), particularly around transparency and quality assurance. I will make enquiries.
