### ISSUE TITLE
Add pull request template 

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/FLINT#51]
**Is your feature request related to a problem? Please describe.**
Adding a pull request template will make it easier for contributors and maintainers to review the code since they will first have to meet the checklist provided in the pull request template to be eligible for the review.

**Describe the solution you'd like**
Add pull request template markdown file to .github folder.

**Comment by Patamap** [comment]
@Tlazypanda  what do you suggest the detail for the pull request template?

**Comment by Tlazypanda** [comment]
Hey @Patamap I have opened a sample PR template here #52 We can modify it according to your input :tada:

**Comment by Patamap** [comment]
@Tlazypanda @gmajan  
can we have a similar pull request labels, as well as issues and the detail, is more towards to coding? 

**Topics:**  _Feature title in the environment?_  
**Detail:** 
**Description**: _Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._

**How Has This Been Tested?** 
_Unit test <Y/N> 
E2E test <Y/N>_
_Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration._

**Checklist:**
 _My code follows the style guidelines of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 I have made corresponding changes to the documentation
 My changes generate no new warnings
 Any dependent changes have been merged and published in downstream modules_

_@mentions of the person or team responsible for reviewing proposed changes_.

**Comment by Tlazypanda** [comment]
Closed #51 via #52 (closing this since merged)
