### ISSUE TITLE
Add badges to README.md to increase readability

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/FLINT#53]
**What does the current documentation state?**
The readme file lacks badges such as code-of-conduct, License, chat options, social handles(if any) and newcomer-friendly. Having these badges at the top in the readme file can help to increase the visibility of these options and increase the readability of the readme file.

**Why do you want to improve the statement?**
To increase readability and enhance quality of readme.

**Proposed statement**
By adding the badges mentioned above.

**Additional info**
For reference: -
https://github.com/publiclab/plots2
https://github.com/learningequality/kolibri
https://github.com/zulip/zulip

**Comment by Tlazypanda** [comment]
Hey @gmajan @patamap adding these badges can help with the discussion we were having on Code Of Conduct not being readily visible as well as for the license :sweat_smile:

**Comment by gmajan** [comment]
why do we add them in develop and not in master?

**Comment by Tlazypanda** [comment]
Hey @gmajan I also realized this later after speaking with @kaskou that develop is the most updated branch by the maintainers :sweat_smile: Hence I am pushing into develop....maybe we can add a note in readme for the same? :sweat_smile:

**Comment by kaskou** [comment]
It's a time for a new release i guess @leitchy and @malfrancis . So, that master branch would be updated .

**Comment by Tlazypanda** [comment]
Closed #53 via #55
