### ISSUE TITLE
Update license of FLINT to latest version

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/FLINT#54]
**Is your feature request related to a problem? Please describe.**
Currently the FLINT License of MPL 2.0 is not updated when compared to FLINT.example and other repositories. As we can see it is not shown as MPL 2.0 License on the right sidebar but as License on the right.

In FLINT repo  

![image](https://user-images.githubusercontent.com/33183263/84536260-13673d80-ad0b-11ea-88de-826c034353d5.png)

In FLINT.example repo  

![image](https://user-images.githubusercontent.com/33183263/84536193-ee72ca80-ad0a-11ea-86c2-ad6886f7ed0a.png)

**Describe the solution you'd like**
Replace with latest version

**Comment by gmajan** [comment]
Thank you. Done.
