### ISSUE TITLE
Repository Missing Description

### ISSUE THREAD

**Issue by abhineet97** [moja-global/FLINT#61]
Hi!

I just noticed that this repository is missing a description:

![Screenshot_2020-06-27_09-16-07](https://user-images.githubusercontent.com/11965776/85914007-3b03ed00-b857-11ea-82cf-ca89aedb8217.png)

Is this intentional? If not then, here are some suggestions:

**Description**

> Full Lands INtegration Tool: a modular greenhouse gas accounting system for the land sector.

**Topics**

> CPP, climate-change, linux-foundation

**Comment by gmajan** [comment]
Missing description is not intentional. 
You suggestions are great. 
Thx
