### ISSUE TITLE
Error in installing FLINT

### ISSUE THREAD

**Issue by Mohitkumar6122** [moja-global/FLINT#82]
**Describe the bug**
During the installation of FLINT, when running the following command in Powershell
```
 cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=C:/Development/Software/moja -DVCPKG_TARGET_TRIPLET=x64-windows -DENABLE_TESTS=OFF -DENABLE_MOJA.MODULES.ZIPPER=OFF -DCMAKE_TOOLCHAIN_FILE=c:\Development\moja-global\vcpkg\scripts\buildsystems\vcpkg.cmake ..

```
I am getting the error : 
```
Parse error in command line argument: -DENABLE_MOJA
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
```

**Expected behavior**
The command should run and install the following FLINT. 

**Screenshots**
![image](https://i.ibb.co/SN39t6V/Screenshot-2021-01-18-004957.png)

**Operating Environment:**
 - Desktop : Acer Aspire  A7-41G
 - OS : Windows 10
 - other

**Additional context**

**Comment by waridrox** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> During the installation of FLINT, when running the following command in Powershell
> 
> ```
>  cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=C:/Development/Software/moja -DVCPKG_TARGET_TRIPLET=x64-windows -DENABLE_TESTS=OFF -DENABLE_MOJA.MODULES.ZIPPER=OFF -DCMAKE_TOOLCHAIN_FILE=c:\Development\moja-global\vcpkg\scripts\buildsystems\vcpkg.cmake ..
> ```
> 
> I am getting the error :
> 
> ```
> Parse error in command line argument: -DENABLE_MOJA
> Should be: VAR:type=value
> CMake Error: No cmake script provided.
> CMake Error: Problem processing arguments. Aborting.
> ```
> 
> **Expected behavior**
> The command should run and install the following FLINT.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> ![image](https://camo.githubusercontent.com/df9f48d319491bd47d3e5f350853b330e5198155085fc99a9f43486f8054020e/68747470733a2f2f692e6962622e636f2f534e33397436562f53637265656e73686f742d323032312d30312d31382d3030343935372e706e67)
> 
> **Operating Environment:**
> 
> * Desktop : Acer Aspire  A7-41G
> * OS : Windows 10
> * other
> 
> **Additional context**
> Add any other context about the problem here.

@Mohitkumar6122 The CLI commands need to be executed in `Windows command prompt` as oppose to `Windows powershell` that you are using. 

![Command_Prompt_on_Windows_10_RTM](https://user-images.githubusercontent.com/58583793/104880626-e99f8480-5985-11eb-8675-dfec2c74b174.png)

Also please make sure that you have installed all the pre-requisites first before executing this command -
- cmake
- visual studio 
- vcpkg 

as mentioned in the official [docs](https://docs.moja.global/en/latest/DevelopmentSetup/windows_installation.html).
If the problem is still not solved feel free to discuss them here :)

**Comment by Mohitkumar6122** [comment]
> > **Describe the bug**
> > A clear and concise description of what the bug is.
> > During the installation of FLINT, when running the following command in Powershell
> > ```
> >  cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=C:/Development/Software/moja -DVCPKG_TARGET_TRIPLET=x64-windows -DENABLE_TESTS=OFF -DENABLE_MOJA.MODULES.ZIPPER=OFF -DCMAKE_TOOLCHAIN_FILE=c:\Development\moja-global\vcpkg\scripts\buildsystems\vcpkg.cmake ..
> > ```
> > 
> > 
> > I am getting the error :
> > ```
> > Parse error in command line argument: -DENABLE_MOJA
> > Should be: VAR:type=value
> > CMake Error: No cmake script provided.
> > CMake Error: Problem processing arguments. Aborting.
> > ```
> > 
> > 
> > **Expected behavior**
> > The command should run and install the following FLINT.
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> > ![image](https://camo.githubusercontent.com/df9f48d319491bd47d3e5f350853b330e5198155085fc99a9f43486f8054020e/68747470733a2f2f692e6962622e636f2f534e33397436562f53637265656e73686f742d323032312d30312d31382d3030343935372e706e67)
> > **Operating Environment:**
> > 
> > * Desktop : Acer Aspire  A7-41G
> > * OS : Windows 10
> > * other
> > 
> > **Additional context**
> > Add any other context about the problem here.
> 
> @Mohitkumar6122 The CLI commands need to be executed in `Windows command prompt` as oppose to `Windows powershell` that you are using.
> 
> ![Command_Prompt_on_Windows_10_RTM](https://user-images.githubusercontent.com/58583793/104880626-e99f8480-5985-11eb-8675-dfec2c74b174.png)
> 
> Also please make sure that you have installed all the pre-requisites first before executing this command -
> 
> * cmake
> * visual studio
> * vcpkg
> 
> as mentioned in the official [docs](https://docs.moja.global/en/latest/DevelopmentSetup/windows_installation.html).
> If the problem is still not solved feel free to discuss them here :)

Thanks a lot @waridrox! It is working now.

**Comment by Mohitkumar6122** [comment]
@waridrox.
Now I when start Visual Studio and open the Visual Studio Debugging All properties page, I am not getting anything inside it as mentioned in the following image. <br> 
![Here](https://docs.moja.global/en/latest/_images/Step4.png) <br>
**But I am getting this in my Setup**
<br>
![Here](https://i.ibb.co/Smd93HW/Screenshot-2021-01-19-012834.png)

**Comment by waridrox** [comment]
@Mohitkumar6122 You have probably installed FLINT in the wrong directory and due to this the debugging setup is not able to recognise the path where FLINT and vcpkg libraries are installed. 

Follow the link for the correct method of [installation](https://docs.google.com/document/d/1YYcA1l6GXbXLcJfLEvX0X5V34jcFK9t3r0X6oL6RDzw/edit?usp=drivesdk).

**Comment by Mohitkumar6122** [comment]
Again, Thanks a lot @waridrox for helping me out with the FLINT installation.
