### ISSUE TITLE
Add links to installation videos and fix some links in the README.md of the develop branch

### ISSUE THREAD

**Issue by mavneeK** [moja-global/FLINT#86]
**What does the current documentation state?**
1. The "moja global developer docs" link in the Installation Docs section leads to a "This site can’t be reached" error. 
2. The "moja global's Slack workspace" link in the FAQ section gives a "Page not found" error.
3. The Installation Videos section does not have a link to the videos.

**Why do you want to improve the statement?**
1. The links would be very useful for newcomers/contributors if they are correct. 
2. Adding links to the videos could help new contributors landing directly on the repository page to get started as the videos are very well explained in detail.  

**Proposed statement**
1. The link to "moja global developer docs" is "https://docs.moja.global.com/" and should rather be "https://docs.moja.global". 
2. The link to "moja global's Slack workspace" is "https://github.com/moja-global/FLINT/blob/develop/mojaglobal.slack.com" and should only be "https://mojaglobal.slack.com". 
3. The youtube videos' links for installation could be added in the required sequence.

**Comment by shubhamkarande13** [comment]
Good going @mavneeK!
